In [1]:
import numpy as np

In [2]:
arr= np.array([])
type(arr)

numpy.ndarray

In [3]:
one_d_array = np.array([1,2,3,4,5])

In [4]:
print(one_d_array)

[1 2 3 4 5]


In [5]:
one_d_array.ndim

1

In [6]:
one_d_array.size

5

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [9]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [10]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
two_d_arr = np.arange(10).reshape(2,5)
print(two_d_arr)
np.ravel(two_d_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10).reshape(2,5).T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [15]:
np.arange(10).reshape(2,5).T.shape

(5, 2)

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.max(), arr.min()

(9, 0)

In [18]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [19]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [20]:
arr[5]

5

In [21]:
for element in arr:
    print(element)

0
1
2
3
4
5
6
7
8
9


In [22]:
for element in arr:
    if(element % 2 == 0):
        print(element, "is positive")
    else:
        print(element, "is negative")
      

0 is positive
1 is negative
2 is positive
3 is negative
4 is positive
5 is negative
6 is positive
7 is negative
8 is positive
9 is negative


In [23]:
#a = 33
#b = 33
#if b > a:
 # print("b is greater than a")
#elif a == b:
 # print("a and b are equal")

In [24]:
for element in arr:
    if(element % 2 == 0):
        print(element, "is positive")
    else:
        print("is negative")

0 is positive
is negative
2 is positive
is negative
4 is positive
is negative
6 is positive
is negative
8 is positive
is negative


In [25]:
_2d_arr = np.array([[10,20], [30,40]])
_2d_arr

array([[10, 20],
       [30, 40]])

In [26]:
_2d_arr.transpose()

array([[10, 30],
       [20, 40]])

In [27]:
%%time
np.linalg.inv(_2d_arr) #inverse

CPU times: user 1.03 ms, sys: 187 µs, total: 1.21 ms
Wall time: 1.27 ms


array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [28]:
identity = np.eye(3, dtype=int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
_2d_arr @ _2d_arr #matrix product

array([[ 700, 1000],
       [1500, 2200]])

In [30]:
np.trace(_2d_arr)

50

# Stacking

In [31]:
a = np.arange(0,20,2)
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#vertical sracking
vs= np.vstack([a,b])
vs

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [34]:
hs = np.hstack([a,b])
hs

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])